### PR TITLE
Fixed it

### PR DESCRIPTION
**Pull request by ashumeow**

### CODE REVIEW

**Comment by anishjajodia** [comment]
Hey. 

Have you updated this?

Does this work well now?

**Comment by ashumeow** [comment]
yup!

**Comment by anishjajodia** [comment]
Okay there. So I’ll commit that to the master of mine. 

Aneesh Jajodia
Web Developer

On 25 March 2015 at 15:58:00, Aswini S (notifications@github.com) wrote:

yup!

**Comment by ashumeow** [comment]
:+1:

**Pull request merged**
